# Generated by Django 2.0.5 on 2018-08-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0003_user_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='link',
            field=models.URLField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
