# Generated by Django 2.0.5 on 2018-08-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0005_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
