# Generated by Django 2.0.5 on 2018-08-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0011_auto_20180813_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.CharField(choices=[('ETC', 'ETC'), ('EEE', 'EEE'), ('EE', 'EE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('IT', 'IT'), ('CSE', 'CSE')], max_length=5, verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.IntegerField(verbose_name='Contact no.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=264, unique=True, verbose_name='Email Id.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=256, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='interest',
            field=models.TextField(max_length=1000, verbose_name='What are you interested in?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='link',
            field=models.URLField(max_length=250, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='user',
            name='semester',
            field=models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th'), ('5', '5th'), ('6', '6th'), ('7', '7th'), ('8', '8th')], max_length=1, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.TextField(max_length=1000, verbose_name='What you Know?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='workshop',
            field=models.TextField(max_length=1000, verbose_name='Attended any workshop?'),
        ),
    ]
