# Generated by Django 2.0.5 on 2018-08-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0012_auto_20180813_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.IntegerField(verbose_name='Contact no.:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='interest',
            field=models.TextField(max_length=1000, verbose_name='What are you interested in?:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.TextField(max_length=1000, verbose_name='What you Know?:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='workshop',
            field=models.TextField(max_length=1000, verbose_name='Attended any workshop?:'),
        ),
    ]
