# Generated by Django 2.0.5 on 2018-08-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0013_auto_20180813_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=264, unique=True, verbose_name='Email Id.:'),
        ),
    ]
