# Generated by Django 2.1.2 on 2019-03-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0014_auto_20180813_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=264, unique=True, verbose_name='Email Id.:')),
                ('semester', models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th'), ('5', '5th'), ('6', '6th'), ('7', '7th'), ('8', '8th')], max_length=1, verbose_name='Semester')),
                ('branch', models.CharField(choices=[('ETC', 'ETC'), ('EEE', 'EEE'), ('EE', 'EE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('IT', 'IT'), ('CSE', 'CSE')], max_length=5, verbose_name='Branch')),
                ('link', models.URLField(max_length=250, verbose_name='link')),
                ('skills', models.CharField(max_length=10000, verbose_name='What you Know?:')),
                ('interest', models.CharField(max_length=10000, verbose_name='What are you interested in?:')),
                ('workshop', models.CharField(max_length=10000, verbose_name='Attended any workshop?:')),
                ('contact', models.IntegerField(verbose_name='Contact no.:')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='interest',
            field=models.CharField(help_text='(e.g. Python,Java,PCB designing,Circuiting,Android Development....etc....)', max_length=10000, verbose_name='What are you interested in?:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='link',
            field=models.CharField(help_text='(also give link if uploaded on social sites)', max_length=10000, verbose_name='What Projects done till now?:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.CharField(help_text='(e.g. Python,Java,PCB designing,Circuiting,Android Development....etc....)', max_length=10000, verbose_name='What you Know?:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='workshop',
            field=models.CharField(help_text='(e.g.Android development,Drone making,Robotics....etc..)', max_length=10000, verbose_name='Attended any workshop?:'),
        ),
    ]
