# Generated by Django 2.1.2 on 2019-03-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0016_auto_20190309_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paid',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=5, verbose_name='PAID'),
        ),
        migrations.AddField(
            model_name='user_new',
            name='paid',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=5, verbose_name='PAID'),
        ),
    ]
