# Generated by Django 2.1.2 on 2019-03-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0018_staff_sudent_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudent_choice',
            name='question10',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='question10'),
        ),
        migrations.AddField(
            model_name='sudent_choice',
            name='question11',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='question11'),
        ),
        migrations.AddField(
            model_name='sudent_choice',
            name='question12',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='question12'),
        ),
        migrations.AddField(
            model_name='sudent_choice',
            name='question13',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='question13'),
        ),
        migrations.AddField(
            model_name='sudent_choice',
            name='question14',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='question14'),
        ),
        migrations.AddField(
            model_name='sudent_choice',
            name='question15',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='question15'),
        ),
        migrations.AddField(
            model_name='sudent_choice',
            name='question16',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='question16'),
        ),
        migrations.AddField(
            model_name='sudent_choice',
            name='question17',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='question17'),
        ),
        migrations.AddField(
            model_name='sudent_choice',
            name='question18',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='question18'),
        ),
        migrations.AddField(
            model_name='sudent_choice',
            name='question19',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='question19'),
        ),
        migrations.AddField(
            model_name='sudent_choice',
            name='question20',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='question20'),
        ),
        migrations.AddField(
            model_name='sudent_choice',
            name='question21',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='question21'),
        ),
        migrations.AddField(
            model_name='sudent_choice',
            name='question22',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='question22'),
        ),
        migrations.AddField(
            model_name='sudent_choice',
            name='question23',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='question23'),
        ),
        migrations.AddField(
            model_name='sudent_choice',
            name='question24',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='question24'),
        ),
        migrations.AddField(
            model_name='sudent_choice',
            name='question25',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='question25'),
        ),
        migrations.AddField(
            model_name='sudent_choice',
            name='question26',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='question26'),
        ),
        migrations.AddField(
            model_name='sudent_choice',
            name='question27',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='question27'),
        ),
        migrations.AddField(
            model_name='sudent_choice',
            name='question28',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='question28'),
        ),
        migrations.AddField(
            model_name='sudent_choice',
            name='question29',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='question29'),
        ),
        migrations.AddField(
            model_name='sudent_choice',
            name='question3',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='question3'),
        ),
        migrations.AddField(
            model_name='sudent_choice',
            name='question30',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='question30'),
        ),
        migrations.AddField(
            model_name='sudent_choice',
            name='question4',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='question4'),
        ),
        migrations.AddField(
            model_name='sudent_choice',
            name='question5',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='question5'),
        ),
        migrations.AddField(
            model_name='sudent_choice',
            name='question6',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='question6'),
        ),
        migrations.AddField(
            model_name='sudent_choice',
            name='question7',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='question7'),
        ),
        migrations.AddField(
            model_name='sudent_choice',
            name='question8',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='question8'),
        ),
        migrations.AddField(
            model_name='sudent_choice',
            name='question9',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5, verbose_name='question9'),
        ),
    ]
