# Generated by Django 2.1.2 on 2019-03-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0019_auto_20190317_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sudent_choice',
            name='question16',
        ),
        migrations.RemoveField(
            model_name='sudent_choice',
            name='question17',
        ),
        migrations.RemoveField(
            model_name='sudent_choice',
            name='question18',
        ),
        migrations.RemoveField(
            model_name='sudent_choice',
            name='question19',
        ),
        migrations.RemoveField(
            model_name='sudent_choice',
            name='question20',
        ),
        migrations.RemoveField(
            model_name='sudent_choice',
            name='question21',
        ),
        migrations.RemoveField(
            model_name='sudent_choice',
            name='question22',
        ),
        migrations.RemoveField(
            model_name='sudent_choice',
            name='question23',
        ),
        migrations.RemoveField(
            model_name='sudent_choice',
            name='question24',
        ),
        migrations.RemoveField(
            model_name='sudent_choice',
            name='question25',
        ),
        migrations.RemoveField(
            model_name='sudent_choice',
            name='question26',
        ),
        migrations.RemoveField(
            model_name='sudent_choice',
            name='question27',
        ),
        migrations.RemoveField(
            model_name='sudent_choice',
            name='question28',
        ),
        migrations.RemoveField(
            model_name='sudent_choice',
            name='question29',
        ),
        migrations.RemoveField(
            model_name='sudent_choice',
            name='question30',
        ),
    ]
