# Generated by Django 2.1.2 on 2019-04-05 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0022_notice_org_notice_tech'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_new',
            new_name='org_team',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='tech_team',
        ),
    ]
