# Generated by Django 2.1.2 on 2020-05-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0025_auto_20200426_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
