# Generated by Django 2.1.2 on 2020-05-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0027_auto_20200501_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
