# Generated by Django 3.0.5 on 2020-05-14 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0028_post_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AptiOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.CharField(blank=True, max_length=500, verbose_name='Option1')),
                ('option2', models.CharField(blank=True, max_length=500, verbose_name='Option2')),
                ('option3', models.CharField(blank=True, max_length=500, verbose_name='Option3')),
                ('option4', models.CharField(blank=True, max_length=500, verbose_name='Option4')),
            ],
        ),
        migrations.CreateModel(
            name='AptiQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=10000, verbose_name='Write your question here')),
            ],
        ),
        migrations.CreateModel(
            name='AptiRightOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTwo.AptiQuestion', verbose_name='Question:')),
            ],
        ),
        migrations.CreateModel(
            name='AptiStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('semester', models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th'), ('5', '5th'), ('6', '6th'), ('7', '7th'), ('8', '8th')], max_length=1, verbose_name='Semester')),
                ('branch', models.CharField(choices=[('ETC', 'ETC'), ('EEE', 'EEE'), ('EE', 'EE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('IT', 'IT'), ('CSE', 'CSE')], max_length=10, verbose_name='Branch')),
                ('contact', models.IntegerField(verbose_name='Contact no.:')),
                ('marks_obt', models.IntegerField(blank=True, verbose_name='Marks Obtained')),
            ],
        ),
        migrations.CreateModel(
            name='AptiTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.IntegerField(blank=True, verbose_name='Test number')),
            ],
        ),
        migrations.DeleteModel(
            name='final_result',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='Sudent_choice',
        ),
        migrations.AddField(
            model_name='aptistudent',
            name='test_no',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='appTwo.AptiTest', verbose_name='Test no.:'),
        ),
        migrations.AddField(
            model_name='aptiquestion',
            name='test_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTwo.AptiTest', verbose_name='Test no.:'),
        ),
        migrations.AddField(
            model_name='aptioption',
            name='question_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTwo.AptiQuestion', verbose_name='Question:'),
        ),
    ]
