# Generated by Django 3.0.5 on 2020-05-14 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0029_auto_20200514_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptioption',
            name='answer',
            field=models.CharField(choices=[('A', 'option1'), ('B', 'option2'), ('C', 'option3'), ('D', 'option4')], default='A', max_length=1, verbose_name='Right Answer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aptioption',
            name='question_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTwo.AptiQuestion', unique=True, verbose_name='Question:'),
        ),
    ]
