# Generated by Django 3.0.5 on 2020-05-14 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0030_auto_20200514_0737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AptiRightOption',
        ),
    ]
