# Generated by Django 3.0.5 on 2020-05-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0031_delete_aptirightoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aptioption',
            name='answer',
            field=models.CharField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('option4', 'option4')], max_length=10, verbose_name='Right Answer'),
        ),
    ]
