# Generated by Django 3.0.6 on 2020-05-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0033_auto_20200514_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aptitest',
            name='test_number',
            field=models.IntegerField(blank=True, unique=True, verbose_name='Test number'),
        ),
    ]
