# Generated by Django 3.0.6 on 2020-05-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0034_auto_20200514_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptistudent',
            name='exp',
            field=models.ManyToManyField(to='appTwo.AptiOption'),
        ),
    ]
