# Generated by Django 3.0.6 on 2020-05-14 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0035_aptistudent_exp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aptistudent',
            name='exp',
        ),
    ]
