# Generated by Django 3.0.6 on 2020-05-17 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0037_auto_20200517_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptitest',
            name='duration',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
